config/routes.rb
Rails.application.routes.draw do

  root 'users#index'
  
  devise_for :users
  resources :users do
    resources :posts 
  end

  resources :posts do
    resources :likes 
  end
    
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships,   only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show, :index]
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  #liked_usersによって投稿が誰にいいねされているのかを簡単に取得できるようになります

end

app/models/relationship.rb
class Relationship < ApplicationRecord
 belongs_to :follower, class_name: "User"
 belongs_to :followed, class_name: "User"
 validates :follower_id, presence: true
 validates :followed_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post  
  #userがどの投稿にいいねをしているのか簡単に取得できるようにする
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
  foreign_key: "follower_id",
  dependent: :destroy
  has_many :passive_relationships, class_name:  "Relationship",
  foreign_key: "followed_id",
  dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  mount_uploader :picture, PictureUploader
  validates :username,uniqueness: true  
  validate :picture_size
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :database_authenticatable, :validatable, password_length: 4..4

  def email_required?
    false
  end
  def email_changed?
    false
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  def already_liked?(post)
    self.likes.exists?(post_id: post.id)
  end

  private
   def picture_size
    picture.size > 5.megabytes
  end
  end
  

app/models/userlike.rb
class Userlike < ApplicationRecord

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 before_action :authenticate_user!
  
  def create
    @like = current_user.likes.create(post_id: params[:post_id])
    if @like.save
      redirect_back(fallback_location: root_path)
    end
  end
  

  def destroy
    @like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
    @like.destroy
      redirect_back(fallback_location: root_path)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
        @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
        redirect_to "/rooms/#{@message.room_id}"
    else
        redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(params[:post].permit(:user_id, :post_id, :belo, :content))
    @post.user_id = current_user.id
    unless @post.save
      flash[:danger] = "文字を入力してください"
    end
  
    redirect_to user_path(@user)
  end
  
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.all

  end

  def show
    #@user = User.find(params[:user_id])
    @post = Post.find(params[:id])
    #@post = @user.posts.find(params[:id])
    @like = Like.new
  end

  def edit
  end

  def update
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.update(params[:post].permit(:user_id, :post_id, :belo, :content))
    redirect_to root_path
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy
    flash[:success] = "削除しました"
    redirect_to user_path(@user)
  end
  end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create 
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end
  
  def index
    @user = current_user 
    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end

    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?',@user.id)
  end


  def show 
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
        @messages = @room.messages
        @message = Message.new
        @entries = @room.entries
    else
        redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/userlikes_controller.rb
class UserlikesController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!, only: [:show, :edit, :update]
   before_action :correct_user,   only: [:edit, :update]
   
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id 
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(params[:user].permit(:username, :userdes, :usertxt, :picture))

    redirect_to user_path
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

private
 def correct_user
  @user = User.find(params[:id])
  redirect_to root_path unless @user == current_user
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/userlikes_helper.rb
module UserlikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
<h3>いいね件数: <%= @post.likes.count %></h3>
<% if current_user.already_liked?(@post) %>
  <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
<% else %>
  <%= button_to 'いいね', post_likes_path(@post) %>
<% end %>
<h3><%= @post.belo %></h3>
<h3><%= @post.content %></h3>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for ([@user, @user.posts.build]) do |f| %>
  <div class="field">
    <%= f.text_area :belo, placeholder: " 所属" %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "プロフィール" %>
  </div>
  <% if user_signed_in? %>
    <%= f.hidden_field :user_id, :value => current_user.id %>
    <%= f.hidden_field :post_id, :value => @user.id %>
   <% end %>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>


 

app/views/posts/_post.html.erb
<h3><%= link_to post.id, post %></h3>
<h3><%= post.belo %></h3>
<h3><%= post.content %></h3>

<h3>いいね件数: <%= post.likes.count %></h3>
<% if current_user.already_liked?(post) %>
  <%= button_to 'いいねを取り消す', post_like_path(post), method: :delete %>
<% else %>
  <%= button_to 'いいね', post_likes_path(post) %>
<% end %>

<% if  current_user == post.user %>
<div class="cd"><%= link_to '削除', [post.user, post], method: :delete, class: "buttn", date:{confirm: 'Are you sure'} %></div>
 <% end %>
</div>

app/views/posts/index.html.erb
<h2>POSTS</h2>
<div class="post_wrapper">
  <% @user.posts.each do |post| %>
  <div class="post_box">
    <h3 class="title"><%= link_to post.belo, post %></h3>
    <h3 class="title"><%= link_to post.content, post %></h3>
  <% end %>
 </div>

app/views/posts/show.html.erb
<h3><%= @post.belo %></h3>
<h3><%= @post.content %></h3>
<h3>いいね件数: <%= @post.likes.count %></h3>
<% if current_user.already_liked?(@post) %>
  <%= button_to 'いいねを取り消す', post_like_path(@post), method: :delete %>
<% else %>
  <%= button_to 'いいね', post_likes_path(@post) %>
<% end %>
<%= link_to "戻る", @user  %>
<%= link_to "Topに戻る", root_path %>

app/views/rooms/index.html.erb
<h1>DM一覧</h1>
<% @anotherEntries.each do |e| %>
    <%= link_to room_path(e.room.id) do %>
      <%= e.user.username %>とのDM<br>
    <% end %>
  <% end %>

app/views/rooms/show.html.erb
<h1>DM</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>">ユーザー:<%= e.user.username%></a></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
    <% @messages.each do |m| %>
        <strong><%= m.content %></strong>
        <small>by:<strong><a href="/users/<%= m.user_id %>"><%= m.user.username %></a></strong></small>
        <hr>
    <% end %>
 <% else %>
    <h3>メッセージはありません</h3>
 <% end %>

 <%= form_for @message do |f| %>
    <%= f.text_field :content, :placeholder => "メッセージを入力してください", :size => 70 %>
    <%= f.hidden_field :room_id, :value => @room.id %>
    <br>
    <%= f.submit "投稿する" %>
 <% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/userlikes/_userlike.html.erb
<%= render "likes/like", post: post %>

app/views/userlikes/index.html.erb
<h1>Userlikes#index</h1>
<p>Find me in app/views/userlikes/create.html.erb</p>

app/views/userlikes/show.html.erb
<h1>Userlikes#showw</h1>
<p>Find me in app/views/userlikes/destroy.html.erb</p>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-primary" %>
  <% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
<div id="follow_form">
 <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
 <% else %>
  <%= render 'follow' %>
 <% end %>
 </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user,html: { multipart: true }) do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username, class: 'form-control' %>

  <%= f.label :userdes%>
  <%= f.text_field :userdes, class: 'form-control' %>

  <%= f.label :usertxt%>
  <%= f.text_field :usertxt, class: 'form-control' %>
  <%= f.submit "編集", class: "btn btn-primary" %>

  <span class="picture">
  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
  </span>
  
<% end %>


<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 1) {
      alert('Maximum file size is 1MB. Please choose a smaller file.');
    }
  });

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<%= render "users/form" %>

app/views/users/index.html.erb
<h2>USERS</h2>
<div class="post_wrapper">
  <% @users.each do |user| %>
  <div class="post_box">
    <h3 class="title"><%= link_to user.username, user %></h3>
  <% end %>
 </div>

app/views/users/show.html.erb
<h1>Usersshow</h1>
<h3>名前：<%= @user.username %></h3>
<h3>所属：<%= @user.userdes %></h3>
<h3>自己紹介：<%= @user.usertxt %></h3>
<%= image_tag @user.picture.to_s if @user.picture? %>

<% if  @user == current_user  %>
  <%= link_to "編集", edit_user_path(current_user) %>
<% end %>
<%= render @user.posts %>
<%= render "posts/form" %>
<%= link_to "いいねをする", user_posts_path(@user) %>

<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>
<%= render 'follow_form' if user_signed_in? %>

<% if @user.id == current_user.id %>

  <% else %>
  <% if @isRoom == true %>
    <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, :value=> @user.id %>
      <% end %>
      <%= f.submit "チャットを始める" %>
    <% end %>
  <% end %>
<% end %>

  <%= link_to "ユーザー一覧に戻る", users_path %>

  <p><a href="/rooms/<%= @roomId %>">チャットへ</a>

app/views/users/show_follow.html.erb
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <% @users.each do |user| %>
          <p><%= link_to user.username, user %></p>
          <p><%= image_tag user.picture.url if user.picture? %></p>
        <% end %>
      </ul>  
    <% end %>
  </div>